# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action
name: GitHub Metrics (Lowlighter) daily run for @seanpm2001
on:
  # ğŸŒ Think about the planet! No need to update stats too frequently (this will run once per day at 1:00 pm PST)
  schedule: [{cron: "0 13 * * *"}]
  # ğŸ’¡ The following line lets you run workflow manually from the action tab!
  workflow_dispatch: # Not needed
# 25 steps
# âš™ï¸ @seanpm2001 GitHub General
# ğŸ’«ï¸ @seanpm2001 GitHub Achievements
# ğŸ“ˆï¸ @seanpm2001 GitHub Stargazer graph â­ï¸
# ğŸ“Šï¸ @seanpm2001 GitHub Stargazers chart â­ï¸
# ğŸ’³ï¸ @seanpm2001 GitHub Licenses and permissions
# ğŸ“ˆï¸ @seanpm2001 GitHub Licenses with open-source ratio graphs ğŸ’³ï¸
# ğŸ’ @seanpm2001 GitHub Sponsorships
# ğŸ—“ï¸ @seanpm2001 GitHub heatmap Current year calendar
# ğŸ—“ï¸ @seanpm2001 GitHub heatmap Full history calendar
# ğŸš¦ï¸ @Seanpm2001 GitHub Repositories traffic
# ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2020)
# ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2021)
# ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2022)
# ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2023)
# ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2024)
# ğŸ™ï¸ @seanpm2001 GitHub City (2020)
# ğŸ™ï¸ @seanpm2001 GitHub City (2021)
# ğŸ™ï¸ @seanpm2001 GitHub City (2022)
# ğŸ™ï¸ @seanpm2001 GitHub City (2023)
# ğŸ™ï¸ @seanpm2001 GitHub City (2024)
# ğŸ·ï¸ @seanpm2001 GitHub starred Labels â­ï¸
# ğŸï¸ @seanpm2001 GitHub starred topics Icons â­ï¸
# ğŸ“…ï¸ @seanpm2001 GitHub Half-year isometric calendar ğŸ”³ï¸
# ğŸ“…ï¸ @seanpm2001 GitHub Full-year isometric calendar ğŸ”³ï¸
# ğŸ’¬ï¸ @seanpm2001 GitHub Discussions ğŸ—¨ï¸
# If the workflow fails, remove this line from every section except for step 1, 2, and 7
# Future todo: keep an updated fork and switch: uses: lowlighter/metrics@latest to seanpm2001/Lowlighter_Metrics@latest
# Should export to 25 separate SVG files
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: lowlighter/metrics@latest
      - name: âš™ï¸ @seanpm2001 GitHub General   
        uses: lowlighter/metrics@latest
        # if: ${{ success() || failure() }}
        with:
          filename: GitHub_Stats_B_GitHub_Languages.svg
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes
      # Step 2
      - uses: lowlighter/metrics@latest
      - name: ğŸ’«ï¸ @seanpm2001 GitHub Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Achievements.svg
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
      # Step 3
      - uses: lowlighter/metrics@latest
      - name: ğŸ“ˆï¸ @seanpm2001 GitHub Stargazer graph â­ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Stargazers_Graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
      # Step 4
      - uses: lowlighter/metrics@latest
      - name: ğŸ“Šï¸ @seanpm2001 GitHub Stargazers chart â­ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Stargazers_Chart.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
      # Step 5
      - uses: lowlighter/metrics@latest
      - name: ğŸ’³ï¸ @seanpm2001 GitHub Licenses and permissions
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Licenses_Overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
      # Step 6
      - uses: lowlighter/metrics@latest
      - name: ğŸ“ˆï¸ @seanpm2001 GitHub Licenses with open-source ratio graphs ğŸ’³ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Licenses_Ratio.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes
      # Step 7
      - uses: lowlighter/metrics@latest
      - name: ğŸ’ @seanpm2001 GitHub Sponsorships
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Sponsorships.svg
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          base: ""
          plugin_sponsorships: yes
      # Step 8
      - uses: lowlighter/metrics@latest
      - name: ğŸ—“ï¸ @seanpm2001 GitHub heatmap Current year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Calendar_2024.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
      # Step 9
      - uses: lowlighter/metrics@latest
      - name: ğŸ—“ï¸ @seanpm2001 GitHub heatmap Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Calendar_2020-Present.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
      # Step 10
      - uses: lowlighter/metrics@latest
      - name: ğŸš¦ï¸ @Seanpm2001 GitHub Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_GitHub_Repository_Traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes
      # Step 11
      - uses: lowlighter/metrics@latest
      - name: ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2020)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_Skyline_2020.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2020
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
      # Step 12
      - uses: lowlighter/metrics@latest
      - name: ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2021)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_Skyline_2021.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
      # Step 13
      - uses: lowlighter/metrics@latest
      - name: ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2022)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_Skyline_2022.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
      # Step 14
      - uses: lowlighter/metrics@latest
      - name: ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2023)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_Skyline_2023.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2023
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
      # Step 15
      - uses: lowlighter/metrics@latest
      - name: ğŸŒ†ï¸ @seanpm2001 GitHub Skyline (2024)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_Skyline_2024.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
      # Step 16
      - uses: lowlighter/metrics@latest
      - name: ğŸ™ï¸ @seanpm2001 GitHub City (2020)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_City_2020.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2020
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
      # Step 17
      - uses: lowlighter/metrics@latest
      - name: ğŸ™ï¸ @seanpm2001 GitHub City (2021)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_City_2021.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
      # Step 18
      - uses: lowlighter/metrics@latest
      - name: ğŸ™ï¸ @seanpm2001 GitHub City (2022)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_City_2022.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
      # Step 19
      - uses: lowlighter/metrics@latest
      - name: ğŸ™ï¸ @seanpm2001 GitHub City (2023)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_City_2023.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2023
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
      # Step 20
      - uses: lowlighter/metrics@latest
      - name: ğŸ™ï¸ @seanpm2001 GitHub City (2024)
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_City_2024.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
      # Step 21
      - uses: lowlighter/metrics@latest
      - name: ğŸ·ï¸ @seanpm2001 GitHub starred Labels â­ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_StarredTopics_Labels_20.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 20
      # Step 22
      - uses: lowlighter/metrics@latest
      - name: ğŸï¸ @seanpm2001 GitHub starred topics Icons â­ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_StarredTopics_Icons_60.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 60
          plugin_topics_mode: icons
      # Step 23
      - uses: lowlighter/metrics@latest
      - name: ğŸ“…ï¸ @seanpm2001 GitHub Half-year isometric calendar ğŸ”³ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_HalfYear_IsometricCalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
      # Step 24
      - uses: lowlighter/metrics@latest
      - name: ğŸ“…ï¸ @seanpm2001 GitHub Full-year isometric calendar ğŸ”³ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001_GitHub_FullYear_IsometricCalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      # Step 25
      - uses: lowlighter/metrics@latest
      - name: ğŸ’¬ï¸ @seanpm2001 GitHub Discussions ğŸ—¨ï¸
        uses: lowlighter/metrics@latest
        with:
          filename: GitHub_Stats_B_Seanpm2001-GitHub-Discussions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 0
#      - name: ğŸ¦‘ Splatoon
#      - uses: lowlighter/metrics@latest
#
#        with:
#          filename: splatoon.svg
#          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
#          base: ""
#          output_action: gist
#          committer_gist: ${{ secrets.GIST }}
#          plugin_splatoon: yes
#          plugin_splatoon_token: ${{ secrets.SPLATOON_TOKEN }}
#          plugin_splatoon_statink: yes
#          plugin_splatoon_statink_token: ${{ secrets.SPLATOON_STATINK_TOKEN }}
#          plugin_splatoon_sections: salmon-run
#          plugin_splatoon_salmon_limit: 2
#          extras_css: |
#            h2 { display: none !important; }
#            .match:not(:last-child) { padding-bottom: 4px; }
#      - name: ğŸ¦‘ Medias
#
#      - uses: lowlighter/metrics@latest
#        with:
#          filename: medias.svg
#          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
#          base: ""
#          config_order: anilist, music
#          output_action: gist
#          committer_gist: ${{ secrets.GIST }}
#          plugin_anilist: yes
#          plugin_anilist_medias: anime
#          plugin_anilist_sections: favorites, characters
#          plugin_anilist_limit: 2
#          plugin_anilist_limit_characters: 22
#          plugin_music: yes
#          plugin_music_playlist: ${{ secrets.PLAYLIST }}
#          plugin_music_limit: 9
#      - name: ğŸ¦‘ Sponsors
#
#      - uses: lowlighter/metrics@latest
#        with:
#          filename: sponsors.svg
#          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
#          base: ""
#          output_action: gist
#          committer_gist: ${{ secrets.GIST }}
#          plugin_sponsors: yes
#          plugin_sponsors_past: yes
#          plugin_sponsorships: yes
#          plugin_sponsorships_sections: amount

# File info
# File version: 5 (2024, Wednesday, March 27th at 04:50 pm PST)
